sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install pipenv --upgrade-strategy=only-if-needed
  - pipenv install --dev
script:
  - pipenv run coverage run --source=httprunner -m unittest discover
after_success:
  - pipenv run coveralls