sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install coverage
  - pip install coveralls
  - pip install flask
  - python setup.py install
script:
  - coverage run --source=httprunner -m unittest discover
after_success:
  - coveralls