site_name: HttpRunner Docs
pages:
    - index.md
    - Introduction.md
    - Installation.md
    - quickstart.md
    - write-testcases.md
    - run-testcases.md
    - load-test.md
    - development.md
    - FAQ.md
theme: material
google_analytics:
  - 'UA-114587036-1'
  - 'auto'
